import type { InferenceStepConfig } from './types'
import { CASE00_TEMPLATES, CASE01_TEMPLATES } from './templates'

export const CASE00_STEP: InferenceStepConfig = {
  stepId: 'case00_b6',
  label: 'Boot 初步分析',
  keywords: [
    { pattern: /CASE-2041-0001|案件编号/, weight: 3, label: '案件识别' },
    { pattern: /钓鱼|phishing/, weight: 3, label: '事件类型' },
    { pattern: /东海银行|东海/, weight: 2, label: '委托方' },
    { pattern: /陆明远/, weight: 1, label: '对接人' },
    { pattern: /1[,，]?183|1183/, weight: 2, label: '事件规模-邮件数' },
    { pattern: /47/, weight: 2, label: '事件规模-凭证泄露数' },
    { pattern: /11/, weight: 1, label: '事件规模-转账数' },
    { pattern: /384[,，]?000|384000|38万/, weight: 2, label: '事件规模-金额' },
    { pattern: /钓鱼域名|域名/, weight: 1, label: '证据类型' },
    { pattern: /追踪|源头/, weight: 1, label: '目标' },
  ],
  triggerWords: [],
  unlockEvidence: undefined,
  templates: CASE00_TEMPLATES,
  noiseWords: ['祝工作顺利', '欢迎上线', 'ops@eda.sec', 'eda@eda.sec', 'Tier-1', '运营方'],
  noiseEffect: 'B 级输出中插入干扰段落',
  specialLogic: null,
}

export const CASE01_STEPS: InferenceStepConfig[] = CASE01_TEMPLATES.map((tmpl, i) => {
  const stepConfigs: Array<Omit<InferenceStepConfig, 'templates'>> = [
    {
      stepId: 'case01_step01',
      label: '钓鱼邮件溯源',
      keywords: [
        { pattern: /donghai-verify/, weight: 3, label: '钓鱼域名' },
        { pattern: /noreply@donghai/, weight: 2, label: '实际发件地址' },
        { pattern: /2041-03-15|03-15|3月15/, weight: 2, label: '发送日期' },
        { pattern: /24小时|验证身份/, weight: 1, label: '社工手法' },
        { pattern: /service@donghai-bank/, weight: 1, label: '伪造发件人' },
      ],
      triggerWords: ['donghai-verify.cn'],
      unlockEvidence: 'evidence_02',
      noiseWords: ['Received:', 'X-Mailer', 'DKIM-Signature', '请勿直接回复', '请勿回复'],
      specialLogic: null,
    },
    {
      stepId: 'case01_step02',
      label: '域名注册溯源',
      keywords: [
        { pattern: /lz_tech/, weight: 3, label: '注册邮箱' },
        { pattern: /刘哲/, weight: 3, label: '注册人' },
        { pattern: /03-10|03-11|03-12/, weight: 2, label: '注册日期' },
        { pattern: /三个域名|3\s*个/, weight: 2, label: '模式识别' },
        { pattern: /vps996/, weight: 1, label: '服务器线索' },
      ],
      triggerWords: ['lz_tech@163.com'],
      unlockEvidence: 'evidence_03',
      specialLogic: null,
    },
    {
      stepId: 'case01_step03',
      label: '邮箱追踪',
      keywords: [
        { pattern: /138[-]?2771[-]?9403|13827719403/, weight: 3, label: '注册手机' },
        { pattern: /深圳|南山/, weight: 2, label: '地理定位' },
        { pattern: /vps996|服务器续费/, weight: 2, label: '攻击基础设施' },
        { pattern: /113[.]89/, weight: 1, label: 'IP段' },
        { pattern: /群发|1[,，]?183/, weight: 1, label: '攻击规模确认' },
      ],
      triggerWords: ['138-2771-9403', '13827719403'],
      unlockEvidence: 'evidence_04',
      specialLogic: null,
    },
    {
      stepId: 'case01_step04',
      label: '通信分析',
      keywords: [
        { pattern: /0755-8832-6617/, weight: 3, label: '高频联络固话' },
        { pattern: /刘哲/, weight: 2, label: '身份确认' },
        { pattern: /57\s*条|57条|群发/, weight: 2, label: '攻击行为证据' },
        { pattern: /189-7654-3210/, weight: 1, label: '关联号码' },
        { pattern: /8\s*次|27分/, weight: 1, label: '通话频率' },
      ],
      triggerWords: ['0755-8832-6617'],
      unlockEvidence: 'evidence_05',
      specialLogic: null,
    },
    {
      stepId: 'case01_step05',
      label: '号码追踪',
      keywords: [
        { pattern: /瑞泽信息技术|瑞泽/, weight: 3, label: '公司名' },
        { pattern: /南山区科技园|创智大厦/, weight: 2, label: '地址' },
        { pattern: /2041-01-15|01-15/, weight: 1, label: '开通日期' },
      ],
      triggerWords: ['瑞泽信息技术', '瑞泽'],
      unlockEvidence: 'evidence_06',
      specialLogic: null,
    },
    {
      stepId: 'case01_step06',
      label: '嫌疑人确认',
      keywords: [
        { pattern: /刘哲/, weight: 3, label: '身份锁定-刘哲' },
        { pattern: /法定代表人|法人|100%/, weight: 3, label: '身份锁定-法人' },
        { pattern: /2041-01-05|成立日期/, weight: 2, label: '时间线起点' },
        { pattern: /实缴.*0|实缴资本.*0/, weight: 2, label: '壳公司特征-实缴' },
        { pattern: /共享办公|WeWork|5\s*家/, weight: 1, label: '非实体经营' },
      ],
      triggerWords: ['刘哲'],
      unlockEvidence: 'evidence_07',
      specialLogic: 'step06_dual_trigger',
    },
    {
      stepId: 'case01_step07',
      label: '关键交叉发现',
      keywords: [
        { pattern: /刘哲/, weight: 3, label: '嫌疑人' },
        { pattern: /03-14|23[:]?47/, weight: 3, label: '异常记录-时间' },
        { pattern: /¥500|500元/, weight: 3, label: '异常记录-金额' },
        { pattern: /47|47人|47名/, weight: 2, label: '总数' },
        { pattern: /384[,，]?200|384200/, weight: 1, label: '总金额' },
      ],
      triggerWords: ['测试', '自己的账户', '验证流程', '自测'],
      unlockEvidence: 'evidence_08',
      specialLogic: null,
    },
    {
      stepId: 'case01_step08',
      label: '资金追踪',
      keywords: [
        { pattern: /8847|尾号\s*8847/, weight: 3, label: '资金去向' },
        { pattern: /381[,，]?500|381500/, weight: 2, label: '转出总额' },
        { pattern: /过水|停留时间|23\s*分钟/, weight: 2, label: '行为模式' },
        { pattern: /2041-01-18|开户/, weight: 1, label: '时间线' },
      ],
      triggerWords: ['8847'],
      unlockEvidence: 'evidence_09',
      specialLogic: null,
    },
    {
      stepId: 'case01_step09',
      label: '资金链分析',
      keywords: [
        { pattern: /海口/, weight: 3, label: '地理线索' },
        { pattern: /8847/, weight: 3, label: '追查目标-账号' },
        { pattern: /持有人|户主|谁/, weight: 3, label: '追查目标-持有人' },
        { pattern: /ATM|取现/, weight: 2, label: '洗钱手段-ATM' },
        { pattern: /加密货币|BTC|USDT/, weight: 1, label: '洗钱手段-加密' },
        { pattern: /第三方支付|支付宝|微信/, weight: 1, label: '洗钱手段-第三方' },
      ],
      triggerWords: ['8847', '海口', '持有人', '户主'],
      unlockEvidence: 'evidence_10',
      specialLogic: null,
    },
    {
      stepId: 'case01_step10',
      label: '第二嫌疑人锁定',
      keywords: [
        { pattern: /陈芳/, weight: 3, label: '第二嫌疑人' },
        { pattern: /189-7654-3210/, weight: 3, label: '关联号码-回响' },
        { pattern: /海口|龙华区/, weight: 2, label: '地理验证' },
        { pattern: /2041-02-20/, weight: 1, label: '开户时间' },
      ],
      triggerWords: ['陈芳', '189-7654-3210', '刘哲', '通话记录'],
      unlockEvidence: 'evidence_11',
      specialLogic: 'step10_echo',
    },
    {
      stepId: 'case01_step11',
      label: '时间轴验证',
      keywords: [
        { pattern: /攻击链|证据链|完整/, weight: 3, label: '全局判断' },
        { pattern: /刘哲/, weight: 3, label: '双嫌疑人-刘哲' },
        { pattern: /陈芳/, weight: 3, label: '双嫌疑人-陈芳' },
        { pattern: /准备期|46\s*天|2[.]?\s*5\s*个月/, weight: 2, label: '预谋程度' },
        { pattern: /03-14.*19[:]?07|致电陈芳/, weight: 2, label: '协作证据' },
      ],
      triggerWords: ['完整', '重建', '攻击链', '证据链', '报告'],
      unlockEvidence: undefined,
      specialLogic: null,
    },
    {
      stepId: 'case01_step12',
      label: '最终分析报告',
      keywords: [
        { pattern: /刘哲/, weight: 3, label: '主犯' },
        { pattern: /陈芳/, weight: 3, label: '同伙' },
        { pattern: /钓鱼|donghai-verify/, weight: 2, label: '攻击手法' },
        { pattern: /384[,，]?200|384200/, weight: 2, label: '总金额' },
        { pattern: /3301|8847/, weight: 2, label: '资金链' },
        { pattern: /01-05|准备期/, weight: 1, label: '时间线' },
        { pattern: /ATM|加密货币/, weight: 1, label: '洗钱手段' },
      ],
      triggerWords: [],
      unlockEvidence: undefined,
      specialLogic: null,
    },
  ]

  const config = stepConfigs[i]
  return {
    ...config,
    templates: { A: tmpl.A, B: tmpl.B, C: tmpl.C },
  }
})
